parameters:
#    itaw_message.example.class: itaw\MessageBundle\Example

services:
#    itaw_message.example:
#        class: %itaw_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
