itaw_forum_homepage:
    pattern:  /
    defaults: { _controller: itawForumBundle:Page:index }
    
itaw_forum_login_check:
    pattern:  /sec/lc/{username}
    defaults: { _controller: itawForumBundle:Page:loginCheck }
    options:
        expose: true
        
itaw_forum_login_state:
    pattern:  /sec/ls/{username}
    defaults: { _controller: itawForumBundle:User:loginState }
    
itaw_forum_forums:
    pattern:  /forums
    defaults: { _controller: itawForumBundle:Page:forums }
    
itaw_forum_show_forum:
    pattern:  /forums/{forum_slug}
    defaults: { _controller: itawForumBundle:Page:showForum }

#forum crud
itaw_forum_create_forum:
    pattern:  /forums/create
    defaults: { _controller: itawForumBundle:Forum:create }
    
itaw_forum_update_forum:
    pattern:  /forums/{forum_slug}/update
    defaults: { _controller: itawForumBundle:Forum:update }
    
itaw_forum_delete_forum:
    pattern:  /forums/{forum_slug}/delete
    defaults: { _controller: itawForumBundle:Forum:delete }
    
#thread crud
itaw_forum_create_thread:
    pattern:  /forums/{forum_slug}/thread/create
    defaults: { _controller: itawForumBundle:Thread:create }
    
itaw_forum_show_thread:
    pattern:  /forums/{forum_slug}/thread/{thread_slug}
    defaults: { _controller: itawForumBundle:Page:showThread }
    
itaw_forum_update_thread:
    pattern:  /forums/{forum_slug}/thread/{thread_slug}/update
    defaults: { _controller: itawForumBundle:Thread:update }
    
itaw_forum_delete_thread:
    pattern:  /forums/{forum_slug}/thread/{thread_slug}/delete
    defaults: { _controller: itawForumBundle:Thread:delete }
    
#post crud
itaw_forum_create_post:
    pattern:  /forums/{forum_slug}/thread/{thread_slug}/post/answer
    defaults: { _controller: itawForumBundle:Post:create }

itaw_forum_read_post:
    pattern:  /forums/{forum_slug}/thread/{thread_slug}/post/{post_id}
    defaults: { _controller: itawForumBundle:Post:read }
    
itaw_forum_update_post:
    pattern:  /forums/{forum_slug}/thread/{thread_slug}/post/{post_id}/update
    defaults: { _controller: itawForumBundle:Post:update }
    
itaw_forum_delete_post:
    pattern:  /forums/{forum_slug}/thread/{thread_slug}/post/{post_id}/delete
    defaults: { _controller: itawForumBundle:Post:delete }