parameters:
#    itaw_forum.example.class: itaw\ForumBundle\Example

services:
#    itaw_forum.example:
#        class: %itaw_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
