#user
itaw_forum_api_user:
    pattern:  /users/{id}
    defaults: { _controller: itawForumApiBundle:User:getObject }
    methods: [GET]
    requirements:
        page:  \d+
    
itaw_forum_api_user_like_name:
    pattern:  /users/likeUsername/{username}
    defaults: { _controller: itawForumApiBundle:User:getUsersLikeName }
    methods: [GET]
