parameters:
#    itaw_forum_api.example.class: itaw\ForumApiBundle\Example

services:
#    itaw_forum_api.example:
#        class: %itaw_forum_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
