itaw_admin:
    resource: "@itawAdminBundle/Resources/config/routing.yml"
    prefix:   /

itaw_message:
    resource: "@itawMessageBundle/Resources/config/routing.yml"
    prefix:   /messages

itaw_forum_api:
    resource: "@itawForumApiBundle/Resources/config/routing.yml"
    prefix:   /api

itaw_template:
    resource: "@itawTemplateBundle/Resources/config/routing.yml"
    prefix:   /template
    
itaw_forum:
    resource: "@itawForumBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        expose: true

itaw_user:
    resource: "@itawUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    