itaw_forum_api:
    resource: "@itawForumApiBundle/Resources/config/routing.yml"
    prefix:   /api

itaw_template:
    resource: "@itawTemplateBundle/Resources/config/routing.yml"
    prefix:   /template
    
itaw_forum:
    resource: "@itawForumBundle/Resources/config/routing.yml"
    prefix:   /

itaw_user:
    resource: "@itawUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    