parameters:
#    itaw_admin.example.class: itaw\AdminBundle\Example

services:
#    itaw_admin.example:
#        class: %itaw_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
