itaw_template_js:
    pattern:  /{templateName}/js/{fileName}
    defaults: { _controller: itawTemplateBundle:Template:getJs }
    
itaw_template_css:
    pattern:  /{templateName}/css/{fileName}
    defaults: { _controller: itawTemplateBundle:Template:getCss }
    
itaw_template_fonts:
    pattern:  /{templateName}/fonts/{fileName}
    defaults: { _controller: itawTemplateBundle:Template:getFonts }